ALTER TABLE "Exam" ADD COLUMN "pausesAllowed" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "Exam" ADD COLUMN "forgiveLives" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "Exam" ADD COLUMN "startsAt" DATETIME NULL;
ALTER TABLE "Exam" ADD COLUMN "endsAt" DATETIME NULL;
ALTER TABLE "Exam" ADD COLUMN "expiresAt" DATETIME NULL;
